---
- name: "Update repo"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "auto-remove dependencies"
  become: yes
  apt:
    autoremove: yes

- name: "Install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "unarchive backend files"
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: "Start Backend"
  shell: |
    cd /home/ubuntu/backend/dist
    npm install --legacy-peer-deps
    npm run build
    pm2 stop default
    pm2 start npm --name 'udapeople' -- start
    pm2 ls
